#pragma once

// #define OLED_DISPLAY_128X64
// #define SPLIT_OLED_ENABLE

#pragma once

// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE

// #define PERMISSIVE_HOLD
#define TAPPING_TERM 175
// #define RETRO_TAPPING
//#define HOLD_ON_OTHER_KEY_PRESS

// #undef RGB_MATRIX_MAXIMUM_BRIGHTNESS
// #define RGB_MATRIX_MAXIMUM_BRIGHTNESS 30
// #define SPLIT_TRANSPORT_MIRROR
// #define SPLIT_LAYER_STATE_ENABLE
// #define SPLIT_MODS_ENABLE

// #define RGB_MATRIX_SLEEP
// #define RGB_TRIGGER_ON_KEYDOWN

// #define SPLIT_ACTIVITY_ENABLE
// #define OLED_TIMEOUT 40000
// #define RGB_MATRIX_TIMEOUT 40000