OLED_ENABLE = yes
ENCODER_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
CONVERT_TO=liatris
SPLIT_KEYBOARD = yes
CAPS_WORD_ENABLE = yes
LAYER_LOCK_ENABLE = yes


RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
WS2812_DRIVER = vendor
RGB_MATRIX_DRIVER = ws2812
RGB_MATRIX_CUSTOM_USER = yes