OLED_ENABLE = no
ENCODER_ENABLE = no
KEY_OVERRIDE_ENABLE = no
CONVERT_TO=liatris
SPLIT_KEYBOARD = no
CAPS_WORD_ENABLE = yes
LAYER_LOCK_ENABLE = yes


RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
WS2812_DRIVER = vendor
RGB_MATRIX_DRIVER = ws2812
RGB_MATRIX_CUSTOM_USER = no